[package]
name = "echo"
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.3", features = ["ws"]}
futures-util = "0.3"
mediasoup = "0.9"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "1.14", features = ["rt-multi-thread", "macros"]}
tower-http = {version = "0.1", features = ["fs"]}
