[package]
name = "rust-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "1.0.11"
rand = "0.8.5"
reqwest = "0.11.11"
tokio = { version = "1.20.0", features = ["full"] }
