[package]
name = "rust-examples"
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
futures-util = "0.3"
log = "0.4"
tokio = {version = "1.14", features = ["full"]}
tokio-tungstenite = "0.16"
tungstenite = "0.16.0"
url = "2.2.2"
